### ISSUE TITLE
Сделать "How to" понятнее и полнее

### ISSUE THREAD

**Issue by ashomokdev** [unickq/privat24-taxer#1]
Добрый день. Очень хочу использовать ваш продукт для моего ФОП, но инструкция по запуску оказалась для меня непосильной. В частности не понятно, как Получить document.cookie в консоли браузера 
Я готова оплатить символически 25 USD за полную видео инструкцию на ютубе как использовать privat24-taxer.
Мой емейл ashomokdev@gmail.com

**Comment by unickq** [comment]
@ashomokdev, 

открыть devtools -> console -> набрать ‘document.cookie’

https://itectec.com/superuser/how-to-view-add-or-edit-cookies-in-google-chrome/

**Comment by ashomokdev** [comment]
Worked now! Thank you so much!

**Comment by unickq** [comment]
Please add a ⭐️ to this repo if it worked for you. So more people be capable to find it 😏
