### ISSUE TITLE
Трохи оновити API

### ISSUE THREAD

**Issue by dittohead** [unickq/privat24-taxer#2]
Вітаю! 
У таксера трохи змінилась апіха, то треба додати масив `operations` і в нього вже класти `data`

або у [src\app.ts](https://github.com/unickq/privat24-taxer/blob/master/src/app.ts) у рядку 44
загорнути
`data`
у
`
{operations: [data]}
`

**Comment by unickq** [comment]
Hey, feel free to create PR 😉

**Comment by dittohead** [comment]
Forgot that is not corporate Github account:D
https://github.com/unickq/privat24-taxer/pull/3

**Comment by unickq** [comment]
TY
